version: "2.4"

services:
  scrapper:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - cache
    environment:
      MEMCACHIER_SERVERS: "cache:11211"
      CAPTCHA_KEY: "44bcf12d53de8363c4e272abb25ca4fd"
  cache:
    image: bitnami/memcached:latest
    ports:
      - "11211:11211"
